angular-hispano/angular-hispano

- VISIÓN.md
> crear: declaración de la visión

- README.md
- package-lock.json
- package.json
- projects/web/src/app/nav/nav.component.html
- projects/web/src/index.html
> cambio: nuevo nombre

- MISIÓN.md
> crear: declaración de la misión

- package-lock.json
- package.json
- projects/web/src/_theme.scss
- projects/web/src/app/app.module.ts
- projects/web/src/app/code-of-conduct/code-of-conduct.component.html
- projects/web/src/app/code-of-conduct/code-of-conduct.component.scss
- projects/web/src/app/code-of-conduct/code-of-conduct.component.spec.ts
- projects/web/src/app/code-of-conduct/code-of-conduct.component.ts
- projects/web/src/app/landing/landing.component.html
- projects/web/src/app/landing/landing.component.scss
- projects/web/src/app/nav/nav.component.html
- projects/web/src/app/nav/nav.component.scss
- projects/web/src/app/nav/nav.component.ts
- projects/web/src/index.html
- projects/web/src/styles.scss
typography
Closes #3
Véalo en vivo: https://angular.lat/coc
> añadir: código de conducta

- .firebaserc
- angular.json
- firebase.json
- package-lock.json
- package.json
utilizar `@angular/fire`'s `ng run web:deploy`
añadir los peer dependencies de `@angular/fire@5.2.0-rc.2`
> build: utilizar @angular/fire's ng run web:deploy

- projects/web/src/app/app.component.html
- projects/web/src/app/app.module.ts
- projects/web/src/app/conferences/conferences.component.html
- projects/web/src/app/conferences/conferences.component.scss
- projects/web/src/app/conferences/conferences.component.spec.ts
- projects/web/src/app/conferences/conferences.component.ts
- projects/web/src/app/footer/footer.component.html
- projects/web/src/app/footer/footer.component.scss
- projects/web/src/app/footer/footer.component.spec.ts
- projects/web/src/app/footer/footer.component.ts
- projects/web/src/app/landing/landing.component.html
- projects/web/src/app/landing/landing.component.scss
- projects/web/src/app/nav/nav.component.html
> añadir: footer y pagina de conferencias

- projects/web/src/app/conferences/conferences.component.ts
Actualizando Próximas conferencias, NG Honduras 2019.
> Conferences

- CONTRIBUTING.md
desde FirebaseVe
Relates to #30
> docs(contributing): añadir contenido para guía de PRs

- projects/web/src/app/nav/nav.component.html
> fix(nav): no debe cerrar en pantallas grandes con ESC

- CONTRIBUTING.md
Cambio de palabras que ayuda a dar un mejor entendimiento a la comunidad
> docs(contributing): cambio de palabras

- .editorconfig
- .vscode/settings.json
- tslint.json
tslint para `.ts`
`.vscode/settings.json` para `.html`
> chore: cambiar line length a 100 max

- docs/admin/upgrade-mattermost.md
No tuve tiempo esta noche para traducirlo todo, pero eso es algo que se puede hacer en el futuro si se desea.
> docs: add an upgrade guide for Mattermost

- projects/web/src/app/conferences/conferences.component.ts
ngSpain y NG Bolivia han cerrado CFPs
> refactor(cfp): elimina enlaces de CFPs cerrados

- package.json
- projects/web/src/app/footer/footer.component.scss
- projects/web/src/app/top-nav/top-nav.component.html
add an npm task for mobile testing on local network
- allows serving on 0.0.0.0 and mobile device connecting at server's IP
> fix(footer,top-nav): a11y improvements

- projects/web/src/app/conferences/conferences.component.html
Entradas es más inclusiva en Español neutro. Boletas es muy local a América Latina.
Closes #82
> chore(traducción): Reemplaza boletas por entradas

- .circleci/config.yml
- package.json
**Descripción:**
Este pull request crea la configuración para Circle CI en el que se corren las siguientes tareas:
1. TSLint
2. StyleLint
3. Unit test
**Tomar en cuenta:**
- El repo se "cachea" en cada build, para mejorar el performance
- Las dependencias se "cachean" hasta que el `package-lock` cambie.
- La configuración queda avanzada para usar executers para correr tests en otros ambientes (si se desea)
- Se creo un workflow para correr tareas en paralelo y aumentar el performance
**¿Como testear el código?:**
1. Admin debe de activar el proyecto en Circle CI (no tengo permisos) 
- Otra opción es hacer fork del proyecto y realizar pruebas desde el fork y no del repo original
2. Configurar GItHub para crear builds en cada PR.
**Pruebas realizadas:**
1. Build sin ningún error en el repo …
> Configuración Circle CI

- projects/web/src/app/conferences/conferences.component.ts
> chore(conferences): actualizar la fecha para NG Honduras

- package-lock.json
- package.json
**Descripción:**
Este pull request corre `npm run format` antes de que los archivos sean "commiteados". 
**Cambios realizados:**
1. Implementacioón de husky en el package.json
**¿Como probar el código?:**
1. Realizar algún cambio que no vaya con alguna de las reglas definidas de `clang-format` en un archivo random de typescript
2. Hacer commit de los cambios
3. Verificar que el archivo haya sido formateado
**Notas:**
- Por ahora solo se corre `npm run format` eventualmente deberían de correr los `test` junto el `lint` con `lint-stage`
> Implementación de Husky para correr scripts previo a commits or push

- docs/admin/letsencrypt-renewal.md
- docs/admin/upgrade-mattermost.md
traducir documentos de actualización de Mattermost
> docs: añadir let's encrypt configuración

- projects/web/src/app/nav.service.ts
- projects/web/src/app/nav/nav.component.ts
- projects/web/src/app/top-nav/top-nav.component.html
- tsconfig.json
Enable Ivy's strict template type checking.
> build: enable strictTemplates, strictFunctionTypes, and strictPropertyInitialization

- package-lock.json
- package.json
- projects/web/src/app/nav.service.ts
- projects/web/src/app/nav/nav.component.html
- projects/web/src/app/nav/nav.component.ts
- projects/web/src/app/top-nav/top-nav.component.html
- tslint.json
- ban Number, String, Boolean types as they can cause some bugs/errors
Reference: https://twitter.com/mgechev/status/1220246042807078912
> build: enable RxJS-specific tslint rules and ban some types

- projects/web/src/app/app.component.spec.ts
- projects/web/src/app/app.component.ts
- projects/web/src/app/app.module.ts
- projects/web/src/app/sw-update.service.ts
App check for new service worker version then display snackbar to update
Fixes #94
> feat(sw): Add snackbar to update app.

- .all-contributorsrc
- README.md
- package.json
- projects/web/src/index.html
- usar `display=swap` para Roboto font
> refactor: traducir sección contribuyentes

- projects/web/src/app/footer/footer.component.html
- projects/web/src/app/landing/landing.component.html
Remplace los enlaces de Mattermost con un enlace de invitación al servidor de Discord.
> chore: replace Mattermost link with Discord link
